title: gbic-pair-programming-2
hero_image: images/banner.png
description: gbic-pair-programming-2 description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Getting started
  - title: Technical setup
  - title: Explore the resources 
  - title: Setting up the classroom for Pair Programming 
  - title: Teacher experience of Pair Programming
  - title: Completion survey
  
